### ISSUE TITLE
Error: Your server's hostname is not fully qualified domain name (FQDN). but i am sure i have set the fully qualified domain name

### ISSUE THREAD

**Issue by qnyblog** [joglomedia/LEMPer#101]
Hello, i am sure i have set the fully qualified domain name, but i always get this error, please help, thank you

Error: Your server's hostname is not fully qualified domain name (FQDN).
In production environment you should use hostname that qualify FQDN format.

nano .env
# In production, server hostname must be valid FQDN format (e.g. hostname.domain.ext).
SERVER_HOSTNAME="789.xxxxxx.work"

# Server IP address, leave it blank for auto detection.
SERVER_IP="68.xxx.x.1x8"

thank you

**Comment by joglomedia** [comment]
Hi @qnyblog 

The error caused by validation regex, the previous validation didn't validate all-numeric labels (exclude TLD source).

I have fixed it, please update your installer to version 2.4.2.

Thanks for reporting the issue.

**Comment by qnyblog** [comment]
Thank you, have a nice day
