### ISSUE TITLE
When add new vhost, get Error "Domain name parameter must be an valid fully qualified domain name (FQDN)!"

### ISSUE THREAD

**Issue by qnyblog** [joglomedia/LEMPer#103]
root@localhost:~/LEMPer-2.4.2# sudo lemper-cli create -u mnbv -d 99.xxx.work -f wordpress -c -F -i -s -P
Error: Domain name parameter must be an valid fully qualified domain name (FQDN)!

For usage information, run this script with --help

Please help, thank you

**Comment by joglomedia** [comment]
Oops, I forgot to update the cli syntax as well x_x

It should now fixed

Please download [v2.4.3](https://github.com/joglomedia/LEMPer/releases/tag/v2.4.3)

Regards

**Comment by qnyblog** [comment]
thank you, have a good day
