### ISSUE TITLE
The LEMPer CLI does not seem to be fully executed

### ISSUE THREAD

**Issue by qnyblog** [joglomedia/LEMPer#105]
When i use this, it only shows "Add new domain name '99.xxx.work' to virtual host."
root@localhost:~/LEMPer# sudo lemper-cli create -u jkkl -d 99.xxx.work -f wordpress --enable-fastcgi-cache --install-app --enable-ssl
Add new domain name '99.xxx.work' to virtual host.

**There is no screen showing the process of installing WordPress, installing FastCGI cache and SSL**

**Comment by joglomedia** [comment]
Hi @qnyblog 

Sorry, I could not reproduce your error :(

I've tried it on my local development environment and production server, but the command seems to work.
See my screen cast here [https://youtu.be/kGvthVr7Ksg](https://youtu.be/kGvthVr7Ksg)

Could you post your system information details?

Regards

**Comment by qnyblog** [comment]
Hello, I know where I was wrong. I put PHP_VERSIONS="7.4 8.0"
DEFAULT_PHP_VERSION="7.4" changed to PHP_VERSIONS="8.0"
DEFAULT_PHP_VERSION="8.0"

Thank you

**Comment by joglomedia** [comment]
> Hello, I know where I was wrong. I put PHP_VERSIONS="7.4 8.0"
> DEFAULT_PHP_VERSION="7.4" changed to PHP_VERSIONS="8.0"
> DEFAULT_PHP_VERSION="8.0"
> 
> Thank you

Glad to hear that,

you are welcome
