### ISSUE TITLE
About Nginx Helper plugin, when i use this script with Nginx FastCgi Cache

### ISSUE THREAD

**Issue by qnyblog** [joglomedia/LEMPer#107]
The Purge Method should be set to "Delete local server cache file" or "Using a GET request to PURGE/url"? thank you

**Comment by joglomedia** [comment]
@qnyblog you could use "Using a GET request to PURGE/url"
the "Delete local server cache file" will not work because we use "isolated" PHP FPM pool.

**Comment by qnyblog** [comment]
Thank you, have a nice day
