### ISSUE TITLE
Feature Request LEMPer

### ISSUE THREAD

**Issue by MiguelEmmara-ai** [joglomedia/LEMPer#138]
Pengen LEMPer yang bisa install wordpress node js app dan laravel kang

Makasih banyak, project nya gokil!

**Comment by joglomedia** [comment]
Hi there,

1. NodeJS sudah masuk dalam Todo list penambahan fitur baru, semoga bisa rilis di versi selanjutnya...

2. Saat ini kamu bisa install WordPress dan Laravel (default app skeleton) melalui command line `lemper-cli`, berikut ini contohnya :

**Install WordPress**

```
sudo lemper-cli site add -d wp.local --framework=wordpress --install-app
```

**Install Laravel App (Skeleton)**

```
sudo lemper-cli site add -d laravel.local --ipv4 127.0.10.33 --framework=laravel --install-app
```

`ipv4` assigns local IP address for local domain

Terima kasih masukannya ..

**Comment by MiguelEmmara-ai** [comment]
mantab kang, ngebantu bgt ini lemper :)
