### ISSUE TITLE
[Bug] Default install Ubuntu 20.04 vsftpd error

### ISSUE THREAD

**Issue by meatlayer** [joglomedia/LEMPer#139]
**Describe the Issue / Bug**

The standard installation ultimately does not finish until the end and stops at an error

```
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
/root/LEMPer/scripts/helper.sh: line 130: cd: too many arguments
Error: Failure running 'cd vsftpd-3.0.5 /', exiting.
```

**To Reproduce**
```
apt-get install git && \
git clone -q https://github.com/joglomedia/LEMPer.git && \
cd LEMPer && \
cp -f .env.dist .env && \
./install.sh
```

**System Information (please complete the following information):**
 - OS: [Ubuntu 20.04.4 LTS"]
 - Shell: [bash 5.0.17(1)-release (x86_64-pc-linux-gnu)]
 - Version [v2.6.4]

**Config File (`.env`)**

[.env](https://github.com/joglomedia/LEMPer/files/9200423/default.env.txt)

**Comment by joglomedia** [comment]
Hi @meatlayer 

It should be fixed now ( #140 ),
could you test and verify it, please.

Thanks for your report :+1: 

Regards
