### ISSUE TITLE
Package 'python' Has No Installation Candidate

### ISSUE THREAD

**Issue by febryanvaldo** [joglomedia/LEMPer#142]
Help me om. Saya mau coba pakai LEMPer, tapi kehalang nih.

Pertama saya sudah lakukan update server `sudo apt-get update -y && sudo apt-get upgrade -y`

Lalu, command 
`sudo apt-get install git`
then,
`git clone -q https://github.com/joglomedia/LEMPer.git `
then,
`cd LEMPer`
then,
`cp -f .env.dist .env`
finally,
`sudo ./install.sh`

Info:
 - OS: Ubuntu 22.04 LTS
 - Provider: UpCloud

![image](https://user-images.githubusercontent.com/28925503/210480661-666de7cb-401d-4fe1-83db-2bad06268622.png)

**Comment by joglomedia** [comment]
@febryanvaldo Mbb, ternyata ada perubahan package python di Ubuntu 22.04, baru sempat update.
Silahkan dicoba rilis terbaru om
