### ISSUE TITLE
permission denied because of listen.owner/group

### ISSUE THREAD

**Issue by chutuananh2k** [joglomedia/LEMPer#151]
use {username} as listen.owner and listen.group causes php-fpm to error.
Change to www-data instead. Better security though.

**Comment by joglomedia** [comment]
Hi @chutuananh2k 
Could you provide detailed information or step by step to reproduce the error?

www-data is global while LEMPer use isolated FPM per system user
have you create the username before? you could skip it to use default LEMPer account

**Comment by joglomedia** [comment]
> use {username} as listen.owner and listen.group causes php-fpm to error. Change to www-data instead. Better security though.

PHP FPM pool configuration has been updated, thanks for discovering this issue
