### ISSUE TITLE
Support RHEL based Distros like AlmaLinux, Rocky Linux and Oracle Linux

### ISSUE THREAD

**Issue by MichalisDBA** [joglomedia/LEMPer#160]
Please make the script work on RedHat Linux based distributions.

The most prominent are:

AlmaLinux
Rocky Linux
Oracle Linux

Thank you.

**Comment by joglomedia** [comment]
Hi @MichalisDBA 
Thanks for your suggestion, but I am sorry that I couldn't able to manage my spare time for that. Porting LEMPer for RHEL-based distribution is currently not in the milestone.
Regards
