### ISSUE TITLE
If feature is not on, install fails

### ISSUE THREAD

**Issue by benfavre** [joglomedia/LEMPer#55]
https://github.com/joglomedia/LEMPer/blob/d3f4ecd86c92b4f2791f3ad7f49bb0a2aece994c/scripts/install_memcached.sh#L138

https://github.com/joglomedia/LEMPer/blob/d3f4ecd86c92b4f2791f3ad7f49bb0a2aece994c/scripts/install_memcached.sh#L179

file "/etc/memcached_memcache.conf" does not exist but "/etc/memcached.conf~" exists

**Comment by benfavre** [comment]
needs something like this before sed
````
if [ ! -f /etc/memcached_memcache.conf ]; then
                run cp /etc/memcached.conf~ /etc/memcached_memcache.conf
            fi
````

**Comment by joglomedia** [comment]
pr #59 contains fix for this issue
