### ISSUE TITLE
Default host created with index.html not found

### ISSUE THREAD

**Issue by benfavre** [joglomedia/LEMPer#65]
The default file for new vhosts has a .html extension but the nginx config does not load index.html  file as index.
renaming index.html to index.php works obviously

**Comment by joglomedia** [comment]
i couldn't reproduce this issue,
did you create the vhost from command line?

**Comment by benfavre** [comment]
My ticket discription is incorrect.
The command I used: 
````
 lemper-cli create -d somedomain.com -f mautic
````

**Comment by joglomedia** [comment]
@benfavre the current Mautic vhost rewrite rule will looking for index.php file, so if there is no index.php the rewite will falling back to 404

**Comment by benfavre** [comment]
Mautic works fine.
I expected to not have a 404 by default

**Comment by joglomedia** [comment]
> Mautic works fine.
> I expected to not have a 404 by default

sorry for late in reply... I have updated the configuration, it should work as expected now.
