### ISSUE TITLE
Mautic config and .gif tracking

### ISSUE THREAD

**Issue by benfavre** [joglomedia/LEMPer#68]
Mautic uses dynamic .gif files for tracking.
The mautic config includes a config file for static content. Removing the gif extension inside that config file fixes tracking.

**Comment by joglomedia** [comment]
@benfavre could you give me an example of the .gif file url? and what's happen if you add this directive to the `etc/nginx/vhost/site_mautic.conf` file?

```
location ~* \.gif$ {
	add_header Cache-Control "no-cache";
	access_log on;
	log_not_found on;
	expires off;
}
```

**Comment by benfavre** [comment]
seems to be working ok for me

**Comment by joglomedia** [comment]
@benfavre thanks for your report
