### ISSUE TITLE
Installation tries to allocate 0MiB swap file and fails

### ISSUE THREAD

**Issue by classbproject** [joglomedia/LEMPer#76]
Hi, I set the appropriate values for packages in `.env` and then tried running `install.sh`. It installed a bunch of packages but never got to installing the EMP stack itself. It said that I did not have an FQDN and that I need to set the hostname to the IP. I instead changed the environment in the `.env` file to `development`. Now I see the following error. What am I missing?

```
Checking swap...
Info: No swap detected.
Creating 0MiB swap...
fallocate: invalid length value specified
Error: Failure running 'fallocate -l 0M /swapfile', exiting.
```

**Comment by classbproject** [comment]
I think this was an EC2 issue. For some reason it did not work with instances with more than 40G of EBS volumes. Its resolved now though. I setup an instance with a slightly lower disk space.

**Comment by classbproject** [comment]
Reopening this issue. Launched a brand new `t4g-small` EC2 instance with 20G disk space. I had initially thought this was something to do larger EBS volumes but apparently it is not. I now see this issue with smaller disk spaces too.

**Comment by joglomedia** [comment]
> Hi, I set the appropriate values for packages in `.env` and then tried running `install.sh`. It installed a bunch of packages but never got to installing the EMP stack itself. It said that I did not have an FQDN and that I need to set the hostname to the IP. I instead changed the environment in the `.env` file to `development`. Now I see the following error. What am I missing?
> 
> ```
> Checking swap...
> Info: No swap detected.
> Creating 0MiB swap...
> fallocate: invalid length value specified
> Error: Failure running 'fallocate -l 0M /swapfile', exiting.
> ```

Hi there

Thanks for reporting the issues,

1. The FQDN requirement means you should naming your hostname with the following format : hostname.domain.ext rather than only 'hostname'
2. The swap creation issue seems caused by the script failed calculating AWS instance memory. Since I not yet tested on AWS, I'll looking for the solution.

Sorry for late in reply
