### ISSUE TITLE
Installation exits on `fail2ban`

### ISSUE THREAD

**Issue by classbproject** [joglomedia/LEMPer#77]
In the `.env` file I've set `fail2ban` install as `false` and yet the script tried to install the package, failed and then exited. I must say this was very frustrating since it died right at the end. I see the following error on the screen. I've tried setting it to `true` and even then it failed. How do I disable this? 

```
[Fail2ban Installation]
cp: cannot create regular file '/etc/fail2ban/filter.d/': No such file or directory
Error: Failure running 'cp -f etc/fail2ban/filter.d/wordpress.conf /etc/fail2ban/filter.d/', exiting.
```

**Comment by joglomedia** [comment]
Hi @classbproject 

Thank you for reporting the issue,
I did a fix to the issue, could you verify it?
The fix is available on 2.0.x branch

Regards
